compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: ./scripts/acc_ds_config.json
  zero3_init_flag: False
  # steps_per_print: 1
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'bf16'
machine_rank: 0
num_machines: 2
num_processes: 8
rdzv_backend: static
same_network: true
use_cpu: false